---
- name: create go path directory
  file: path={{ gopath }} state=directory

- name: download
  get_url: url={{ golang_url }} dest={{ ansible_env.HOME }}/{{ golang_source }}

- name: unarchive
  unarchive: src={{ ansible_env.HOME }}/{{ golang_source }} dest={{ ansible_env.HOME }} copy=no creates={{ goroot }}

- name: rename goroot
  command: mv {{ ansible_env.HOME }}/go {{ ansible_env.HOME }}/.goroot creates={{ goroot }}

- name: get go tools
  command: "{{ goroot }}/bin/go get {{ item }}"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/tools/cmd/vet
    - golang.org/x/tools/cmd/cover
    - github.com/nsf/gocode
    - github.com/lestrrat/peco/cmd/peco
    - github.com/motemen/ghq
  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"
